import type { AppSettings, PiTheme } from '../types';

type ThemeColors = Record<string, string>;

const DEFAULT_FONT_FAMILY = "'Inter', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif";
const DEFAULT_MONO_FONT_FAMILY = "'JetBrains Mono', 'Fira Code', 'Cascadia Code', Consolas, monospace";

const PRIORITY_THEME_NAMES = ['dark', 'light', 'claude-code', 'codex', 'trae'];

const THEME_DISPLAY_NAMES: Record<string, string> = {
  dark: 'Dark',
  light: 'Light',
  'midnight-blue': 'Midnight Blue',
  'forest-canopy': 'Forest Canopy',
  'palette-nocturne': 'Palette Nocturne',
  'rose-quartz': 'Rose Quartz',
  'amber-workbench': 'Amber Workbench',
  'violet-arc': 'Violet Arc',
  'ocean-depths': 'Ocean Depths',
  graphite: 'Graphite',
  'solarized-dark': 'Solarized Dark',
  'solarized-light': 'Solarized Light',
  'nord-frost': 'Nord Frost',
  'dracula-night': 'Dracula Night',
  'catppuccin-mocha': 'Catppuccin Mocha',
  'matcha-latte': 'Matcha Latte',
  'crimson-lab': 'Crimson Lab',
  cyberpunk: 'Cyberpunk',
  'cyberpunk-neon': 'Cyberpunk Neon',
  'star-wars-galaxy': 'Star Wars Galaxy',
  'claude-code': 'Claude Code',
  codex: 'Codex',
  trae: 'Trae',
  'calm-slate': 'Calm Slate',
  'sepia-paper': 'Sepia Paper',
  'high-contrast-dark': 'High Contrast Dark',
  'high-contrast-light': 'High Contrast Light',
  'lavender-mist': 'Lavender Mist',
  'terminal-green': 'Terminal Green',
  coffeehouse: 'Coffeehouse',
  iceberg: 'Iceberg',
};

export const BUILTIN_THEMES: PiTheme[] = [
  {
    name: 'dark',
    colors: {
      accent: '#00aaff',
      border: '#3a3a3e',
      borderAccent: '#00aaff',
      borderMuted: '#2a2a2e',
      success: '#00cc66',
      error: '#ff4444',
      warning: '#ffaa00',
      muted: '#888892',
      dim: '#55555a',
      text: '#e0e0e8',
      thinkingText: '#a0a0b0',
      bg: '#1a1a1e',
      bgSecondary: '#1e1e24',
      bgTertiary: '#24242a',
      bgHover: '#2a2a32',
      titlebarBg: '#151519',
      titlebarText: '#e0e0e8',
      titlebarBorder: '#2a2a2e',
      titlebarHover: '#24242a',
      titlebarActive: '#2d2d38',
      selectedBg: '#2d2d38',
      userMessageBg: '#2d2d38',
      userMessageText: '#e0e0e8',
      customMessageBg: '#2d2d38',
      customMessageText: '#e0e0e8',
      customMessageLabel: '#00aaff',
      toolPendingBg: '#1e1e2e',
      toolSuccessBg: '#1e2e1e',
      toolErrorBg: '#2e1e1e',
      toolTitle: '#00aaff',
      toolOutput: '#c0c0d0',
      mdHeading: '#ffaa00',
      mdLink: '#00aaff',
      mdLinkUrl: '#888892',
      mdCode: '#00ffff',
      mdCodeBlock: '#e0e0e8',
      mdCodeBlockBorder: '#3a3a3e',
      mdQuote: '#888892',
      mdQuoteBorder: '#3a3a3e',
      mdHr: '#3a3a3e',
      mdListBullet: '#00ffff',
      toolDiffAdded: '#00cc66',
      toolDiffRemoved: '#ff4444',
      toolDiffContext: '#888892',
      syntaxComment: '#888892',
      syntaxKeyword: '#00aaff',
      syntaxFunction: '#00ccff',
      syntaxVariable: '#ffaa00',
      syntaxString: '#00cc66',
      syntaxNumber: '#ff66cc',
      syntaxType: '#00ccff',
      syntaxOperator: '#00aaff',
      syntaxPunctuation: '#888892',
      thinkingOff: '#55555a',
      thinkingMinimal: '#00aaff',
      thinkingLow: '#00ccff',
      thinkingMedium: '#00ffff',
      thinkingHigh: '#ff66cc',
      thinkingXhigh: '#ff4444',
      bashMode: '#ffaa00',
    },
  },
  {
    name: 'light',
    colors: {
      accent: '#0066cc',
      border: '#d4d4d8',
      borderAccent: '#0066cc',
      borderMuted: '#e4e4e7',
      success: '#008a3a',
      error: '#cc0000',
      warning: '#b66d00',
      muted: '#71717a',
      dim: '#a1a1aa',
      text: '#18181b',
      thinkingText: '#52525b',
      bg: '#fafafa',
      bgSecondary: '#ffffff',
      bgTertiary: '#f4f4f5',
      bgHover: '#e4e4e7',
      titlebarBg: '#f4f4f5',
      titlebarText: '#18181b',
      titlebarBorder: '#d4d4d8',
      titlebarHover: '#e4e4e7',
      titlebarActive: '#dfe7f3',
      selectedBg: '#e4e4e7',
      userMessageBg: '#f4f4f5',
      userMessageText: '#18181b',
      customMessageBg: '#f4f4f5',
      customMessageText: '#18181b',
      customMessageLabel: '#0066cc',
      toolPendingBg: '#eef2ff',
      toolSuccessBg: '#ecfdf3',
      toolErrorBg: '#fef2f2',
      toolTitle: '#0066cc',
      toolOutput: '#3f3f46',
      mdHeading: '#9a5a00',
      mdLink: '#0066cc',
      mdLinkUrl: '#71717a',
      mdCode: '#007c7c',
      mdCodeBlock: '#18181b',
      mdCodeBlockBorder: '#d4d4d8',
      mdQuote: '#71717a',
      mdQuoteBorder: '#d4d4d8',
      mdHr: '#d4d4d8',
      mdListBullet: '#007c7c',
      toolDiffAdded: '#008a3a',
      toolDiffRemoved: '#cc0000',
      toolDiffContext: '#71717a',
      syntaxComment: '#71717a',
      syntaxKeyword: '#0066cc',
      syntaxFunction: '#0088cc',
      syntaxVariable: '#9a5a00',
      syntaxString: '#008a3a',
      syntaxNumber: '#b83280',
      syntaxType: '#0088cc',
      syntaxOperator: '#0066cc',
      syntaxPunctuation: '#71717a',
      thinkingOff: '#a1a1aa',
      thinkingMinimal: '#0066cc',
      thinkingLow: '#0088cc',
      thinkingMedium: '#007c7c',
      thinkingHigh: '#b83280',
      thinkingXhigh: '#cc0000',
      bashMode: '#9a5a00',
    },
  },
  themeVariant('midnight-blue', {
    accent: '#66d9ff',
    bg: '#07111f',
    bgSecondary: '#0b1728',
    bgTertiary: '#10243b',
    bgHover: '#17324f',
    border: '#24415f',
    borderMuted: '#17283a',
    selectedBg: '#14385a',
    text: '#e6f2ff',
    muted: '#8aa5bd',
    dim: '#567187',
    warning: '#ffd166',
    success: '#57d68d',
    error: '#ff6b7a',
    syntaxString: '#7bd88f',
    syntaxNumber: '#f8a5ff',
  }),
  themeVariant('forest-canopy', {
    accent: '#7ddc8b',
    bg: '#09140d',
    bgSecondary: '#101d14',
    bgTertiary: '#182a1d',
    bgHover: '#203b27',
    border: '#31533a',
    borderMuted: '#203725',
    selectedBg: '#22452d',
    text: '#edf7ee',
    muted: '#93ad98',
    dim: '#667b6a',
    warning: '#e6c75a',
    success: '#6ee78a',
    error: '#ff7a7a',
    mdHeading: '#d7e879',
  }),
  themeVariant('palette-nocturne', {
    accent: '#a9f02a',
    bg: '#050607',
    bgSecondary: '#08090b',
    bgTertiary: '#111316',
    bgHover: '#1a1d20',
    border: '#2b3035',
    borderMuted: '#20242a',
    selectedBg: '#18350a',
    text: '#f7fbff',
    thinkingText: '#c8d4e3',
    muted: '#b7c5d8',
    dim: '#7d8ba0',
    warning: '#ffb232',
    success: '#a9f02a',
    error: '#c62a82',
    titlebarBg: '#050607',
    titlebarText: '#f7fbff',
    titlebarBorder: '#24282e',
    titlebarHover: '#171a1f',
    titlebarActive: '#0e2a1b',
    userMessageBg: '#0b1f16',
    userMessageText: '#f7fbff',
    customMessageBg: '#1b1024',
    customMessageText: '#f7fbff',
    customMessageLabel: '#a9f02a',
    toolPendingBg: '#101316',
    toolSuccessBg: '#102818',
    toolErrorBg: '#2a101e',
    toolTitle: '#a9f02a',
    toolOutput: '#c8d4e3',
    mdHeading: '#ffb232',
    mdLink: '#356aa6',
    mdLinkUrl: '#b7c5d8',
    mdCode: '#c62a82',
    mdListBullet: '#a9f02a',
    syntaxKeyword: '#c62a82',
    syntaxFunction: '#a9f02a',
    syntaxVariable: '#ffb232',
    syntaxString: '#7fd000',
    syntaxNumber: '#ffcc79',
    syntaxType: '#c7ee72',
    syntaxOperator: '#356aa6',
    syntaxPunctuation: '#b7c5d8',
    thinkingMinimal: '#356aa6',
    thinkingLow: '#a9f02a',
    thinkingMedium: '#ffb232',
    thinkingHigh: '#c62a82',
    thinkingXhigh: '#9b0050',
    bashMode: '#ffb232',
  }),
  themeVariant('rose-quartz', {
    accent: '#ff7aa8',
    bg: '#1b1017',
    bgSecondary: '#25141e',
    bgTertiary: '#341a2a',
    bgHover: '#432238',
    border: '#5a2d47',
    borderMuted: '#3b2230',
    selectedBg: '#4b2740',
    text: '#fff0f6',
    muted: '#c599ad',
    dim: '#8f6376',
    warning: '#ffc46b',
    success: '#78d9a4',
    error: '#ff5d73',
  }),
  themeVariant('amber-workbench', {
    accent: '#ffb84d',
    bg: '#17110a',
    bgSecondary: '#21180f',
    bgTertiary: '#302315',
    bgHover: '#3f2f1e',
    border: '#60482c',
    borderMuted: '#3d2d1b',
    selectedBg: '#4d351c',
    text: '#fff4df',
    muted: '#c4aa82',
    dim: '#8a7556',
    warning: '#ffd166',
    success: '#8bd17c',
    error: '#ff745f',
    mdHeading: '#ffce73',
  }),
  themeVariant('violet-arc', {
    accent: '#b794ff',
    bg: '#12101f',
    bgSecondary: '#19152a',
    bgTertiary: '#241d3b',
    bgHover: '#30274d',
    border: '#493c69',
    borderMuted: '#2d2542',
    selectedBg: '#382d5a',
    text: '#f3efff',
    muted: '#aba0c9',
    dim: '#776e94',
    warning: '#ffd166',
    success: '#75dda0',
    error: '#ff7190',
  }),
  themeVariant('ocean-depths', {
    accent: '#4dd8c8',
    bg: '#071817',
    bgSecondary: '#0c2221',
    bgTertiary: '#123230',
    bgHover: '#194642',
    border: '#2a615b',
    borderMuted: '#1a3d3a',
    selectedBg: '#1b504c',
    text: '#e9fffb',
    muted: '#8fb8b1',
    dim: '#5d807a',
    warning: '#f4c95d',
    success: '#69dfa2',
    error: '#ff6f7a',
  }),
  themeVariant('graphite', {
    accent: '#a7b3c4',
    bg: '#111214',
    bgSecondary: '#181a1d',
    bgTertiary: '#22252a',
    bgHover: '#2d3137',
    border: '#424852',
    borderMuted: '#2e333a',
    selectedBg: '#343a44',
    text: '#eef1f5',
    muted: '#a3abb8',
    dim: '#6c7480',
    warning: '#e0b85b',
    success: '#7ed18d',
    error: '#ee6b6e',
  }),
  themeVariant('solarized-dark', {
    accent: '#268bd2',
    bg: '#002b36',
    bgSecondary: '#073642',
    bgTertiary: '#0b3e4b',
    bgHover: '#164b58',
    border: '#315863',
    borderMuted: '#16424e',
    selectedBg: '#174b5a',
    text: '#eee8d5',
    muted: '#93a1a1',
    dim: '#657b83',
    warning: '#b58900',
    success: '#859900',
    error: '#dc322f',
    mdHeading: '#cb4b16',
    syntaxString: '#2aa198',
    syntaxNumber: '#d33682',
  }),
  themeVariant('solarized-light', {
    accent: '#268bd2',
    bg: '#fdf6e3',
    bgSecondary: '#eee8d5',
    bgTertiary: '#e3dcc8',
    bgHover: '#d8d0ba',
    border: '#c9bfa5',
    borderMuted: '#ded6c1',
    selectedBg: '#dbeaf0',
    text: '#073642',
    muted: '#657b83',
    dim: '#93a1a1',
    warning: '#b58900',
    success: '#859900',
    error: '#dc322f',
    mdHeading: '#cb4b16',
    syntaxString: '#2aa198',
    syntaxNumber: '#d33682',
  }),
  themeVariant('nord-frost', {
    accent: '#88c0d0',
    bg: '#2e3440',
    bgSecondary: '#343b49',
    bgTertiary: '#3b4252',
    bgHover: '#434c5e',
    border: '#4c566a',
    borderMuted: '#3b4252',
    selectedBg: '#40556b',
    text: '#eceff4',
    muted: '#d8dee9',
    dim: '#9aa6b8',
    warning: '#ebcb8b',
    success: '#a3be8c',
    error: '#bf616a',
    mdHeading: '#b48ead',
  }),
  themeVariant('dracula-night', {
    accent: '#bd93f9',
    bg: '#282a36',
    bgSecondary: '#303241',
    bgTertiary: '#393c4d',
    bgHover: '#44475a',
    border: '#55586d',
    borderMuted: '#3b3e50',
    selectedBg: '#3f4568',
    text: '#f8f8f2',
    muted: '#bfbfd5',
    dim: '#7e829a',
    warning: '#f1fa8c',
    success: '#50fa7b',
    error: '#ff5555',
    syntaxString: '#f1fa8c',
    syntaxNumber: '#ff79c6',
  }),
  themeVariant('catppuccin-mocha', {
    accent: '#89b4fa',
    bg: '#1e1e2e',
    bgSecondary: '#252537',
    bgTertiary: '#313244',
    bgHover: '#45475a',
    border: '#585b70',
    borderMuted: '#383a4c',
    selectedBg: '#394260',
    text: '#cdd6f4',
    muted: '#a6adc8',
    dim: '#6c7086',
    warning: '#f9e2af',
    success: '#a6e3a1',
    error: '#f38ba8',
    mdHeading: '#fab387',
  }),
  themeVariant('matcha-latte', {
    accent: '#4f9f6f',
    bg: '#f4f7ef',
    bgSecondary: '#ffffff',
    bgTertiary: '#e9efe1',
    bgHover: '#dde8d4',
    border: '#c7d4bd',
    borderMuted: '#dce5d4',
    selectedBg: '#d7ecd8',
    text: '#203126',
    muted: '#647867',
    dim: '#8c9d8c',
    warning: '#b7791f',
    success: '#2f855a',
    error: '#c53030',
  }),
  themeVariant('crimson-lab', {
    accent: '#ff5c7a',
    bg: '#160b10',
    bgSecondary: '#211018',
    bgTertiary: '#321824',
    bgHover: '#442030',
    border: '#663247',
    borderMuted: '#3f2230',
    selectedBg: '#54283a',
    text: '#fff1f4',
    muted: '#c99aa5',
    dim: '#916a73',
    warning: '#ffc857',
    success: '#7ed891',
    error: '#ff4d4f',
  }),
  themeVariant('cyberpunk', {
    accent: '#00f5ff',
    bg: '#10091f',
    bgSecondary: '#180d2c',
    bgTertiary: '#24133e',
    bgHover: '#341a58',
    border: '#5b2e82',
    borderMuted: '#321c4a',
    selectedBg: '#173d62',
    text: '#f9f7ff',
    muted: '#bca8d9',
    dim: '#7c6799',
    warning: '#ffe45e',
    success: '#39ff88',
    error: '#ff3d9a',
    mdHeading: '#ffe45e',
    syntaxString: '#39ff88',
    syntaxNumber: '#ff3d9a',
  }),
  themeVariant('cyberpunk-neon', {
    accent: '#00fff0',
    bg: '#070012',
    bgSecondary: '#0d061f',
    bgTertiary: '#17102f',
    bgHover: '#26154c',
    border: '#6f2cff',
    borderMuted: '#2d1759',
    selectedBg: '#102d55',
    text: '#f8f4ff',
    thinkingText: '#7dfcff',
    muted: '#b592ff',
    dim: '#7353a8',
    warning: '#ffe600',
    success: '#00ff85',
    error: '#ff2d95',
    titlebarBg: '#05000d',
    titlebarHover: '#1b0f36',
    titlebarActive: '#271255',
    userMessageBg: '#1b1140',
    customMessageBg: '#23104a',
    toolPendingBg: '#100d2d',
    toolSuccessBg: '#082d24',
    toolErrorBg: '#341026',
    mdHeading: '#ffe600',
    mdLink: '#00fff0',
    mdCode: '#ff2d95',
    syntaxKeyword: '#ff2d95',
    syntaxFunction: '#00fff0',
    syntaxVariable: '#ffe600',
    syntaxString: '#00ff85',
    syntaxNumber: '#ff7ad9',
    syntaxType: '#b592ff',
    thinkingHigh: '#ffe600',
    thinkingXhigh: '#ff2d95',
  }),
  themeVariant('star-wars-galaxy', {
    accent: '#5bbcff',
    bg: '#05070d',
    bgSecondary: '#0b0f1a',
    bgTertiary: '#121827',
    bgHover: '#1b2639',
    border: '#2f3e57',
    borderMuted: '#1a2434',
    selectedBg: '#102b46',
    text: '#f2f6ff',
    thinkingText: '#b9c8dd',
    muted: '#9aa9bd',
    dim: '#647286',
    warning: '#ffe45c',
    success: '#52d273',
    error: '#ff4f5e',
    titlebarBg: '#03050a',
    titlebarText: '#f7fbff',
    titlebarBorder: '#1d2b43',
    titlebarHover: '#101a2a',
    titlebarActive: '#18263d',
    userMessageBg: '#162238',
    userMessageText: '#f2f6ff',
    customMessageBg: '#111b2d',
    customMessageLabel: '#ffe45c',
    toolPendingBg: '#111827',
    toolSuccessBg: '#0d2517',
    toolErrorBg: '#2e1015',
    toolTitle: '#ffe45c',
    mdHeading: '#ffe45c',
    mdLink: '#5bbcff',
    mdCode: '#52d273',
    mdListBullet: '#ffe45c',
    syntaxKeyword: '#5bbcff',
    syntaxFunction: '#ffe45c',
    syntaxVariable: '#f2f6ff',
    syntaxString: '#52d273',
    syntaxNumber: '#ff6b70',
    syntaxType: '#8fb8ff',
    syntaxOperator: '#ff4f5e',
    thinkingMinimal: '#5bbcff',
    thinkingLow: '#52d273',
    thinkingMedium: '#ffe45c',
    thinkingHigh: '#ff4f5e',
    thinkingXhigh: '#ff2d35',
  }),
  themeVariant('claude-code', {
    accent: '#d87058',
    bg: '#080808',
    bgSecondary: '#101010',
    bgTertiary: '#181818',
    bgHover: '#202020',
    border: '#383838',
    borderMuted: '#202020',
    selectedBg: '#2a211f',
    text: '#f0f0e8',
    thinkingText: '#d8d0c8',
    muted: '#b8b0a8',
    dim: '#707070',
    warning: '#e8a05c',
    success: '#62b579',
    error: '#d87058',
    titlebarBg: '#080808',
    titlebarText: '#f0f0e8',
    titlebarBorder: '#202020',
    titlebarHover: '#181818',
    titlebarActive: '#2a211f',
    userMessageBg: '#181818',
    userMessageText: '#f0f0e8',
    customMessageBg: '#201816',
    customMessageText: '#f0f0e8',
    customMessageLabel: '#d87058',
    toolPendingBg: '#101010',
    toolSuccessBg: '#102018',
    toolErrorBg: '#281512',
    toolTitle: '#d87058',
    toolOutput: '#d8d0c8',
    mdHeading: '#d87058',
    mdLink: '#e08468',
    mdCode: '#e8a05c',
    syntaxKeyword: '#d87058',
    syntaxFunction: '#e8a05c',
    syntaxVariable: '#f0f0e8',
    syntaxString: '#7abf83',
    syntaxNumber: '#d890bc',
    syntaxType: '#c89a7a',
    syntaxOperator: '#d87058',
    thinkingMinimal: '#d87058',
    thinkingLow: '#e08468',
    thinkingMedium: '#e8a05c',
    thinkingHigh: '#d890bc',
    thinkingXhigh: '#d87058',
  }),
  themeVariant('codex', {
    accent: '#6860a8',
    bg: '#101018',
    bgSecondary: '#181820',
    bgTertiary: '#202030',
    bgHover: '#282838',
    border: '#3d3a5f',
    borderMuted: '#282838',
    selectedBg: '#302858',
    text: '#d8d8e8',
    thinkingText: '#b8b4d8',
    muted: '#a8a4c8',
    dim: '#707078',
    warning: '#d8b868',
    success: '#10a37f',
    error: '#e36a8a',
    titlebarBg: '#080818',
    titlebarText: '#d8d8e8',
    titlebarBorder: '#202030',
    titlebarHover: '#202030',
    titlebarActive: '#302858',
    userMessageBg: '#202030',
    userMessageText: '#e8e8f0',
    customMessageBg: '#282040',
    customMessageText: '#e8e8f0',
    customMessageLabel: '#8d84d8',
    toolPendingBg: '#181820',
    toolSuccessBg: '#102820',
    toolErrorBg: '#301827',
    toolTitle: '#8d84d8',
    toolOutput: '#d8d8e8',
    mdHeading: '#f0f0ff',
    mdLink: '#8d84d8',
    mdCode: '#c6c0ff',
    syntaxKeyword: '#8d84d8',
    syntaxFunction: '#b0a8ff',
    syntaxVariable: '#d8d8e8',
    syntaxString: '#78d8b0',
    syntaxNumber: '#e08ac0',
    syntaxType: '#9090d8',
    syntaxOperator: '#8d84d8',
    thinkingMinimal: '#6860a8',
    thinkingLow: '#8d84d8',
    thinkingMedium: '#b0a8ff',
    thinkingHigh: '#d8b868',
    thinkingXhigh: '#e36a8a',
  }),
  themeVariant('trae', {
    accent: '#2ef28a',
    bg: '#050607',
    bgSecondary: '#08090b',
    bgTertiary: '#111316',
    bgHover: '#1a1d20',
    border: '#2b3035',
    borderMuted: '#20242a',
    selectedBg: '#082318',
    text: '#f7fbff',
    thinkingText: '#c8d4e3',
    muted: '#b7c5d8',
    dim: '#7d8ba0',
    warning: '#d7ff5f',
    success: '#2ef28a',
    error: '#ff5f6d',
    titlebarBg: '#050607',
    titlebarText: '#f7fbff',
    titlebarBorder: '#24282e',
    titlebarHover: '#171a1f',
    titlebarActive: '#082318',
    userMessageBg: '#0b1f16',
    userMessageText: '#f7fbff',
    customMessageBg: '#0f1714',
    customMessageText: '#f7fbff',
    customMessageLabel: '#2ef28a',
    toolPendingBg: '#101316',
    toolSuccessBg: '#092818',
    toolErrorBg: '#2a1016',
    toolTitle: '#2ef28a',
    toolOutput: '#c8d4e3',
    mdHeading: '#2ef28a',
    mdLink: '#b7c5d8',
    mdCode: '#2ef28a',
    mdListBullet: '#2ef28a',
    syntaxKeyword: '#2ef28a',
    syntaxFunction: '#f7fbff',
    syntaxVariable: '#c8d4e3',
    syntaxString: '#75ffb4',
    syntaxNumber: '#d7ff5f',
    syntaxType: '#9beec5',
    syntaxOperator: '#2ef28a',
    syntaxPunctuation: '#b7c5d8',
    thinkingMinimal: '#2ef28a',
    thinkingLow: '#75ffb4',
    thinkingMedium: '#b7c5d8',
    thinkingHigh: '#d7ff5f',
    thinkingXhigh: '#ff5f6d',
  }),
  themeVariant('calm-slate', {
    accent: '#7aa2f7',
    bg: '#151922',
    bgSecondary: '#1c2230',
    bgTertiary: '#242b3a',
    bgHover: '#30384a',
    border: '#445064',
    borderMuted: '#2d3545',
    selectedBg: '#2f3d5a',
    text: '#e8edf7',
    muted: '#a2adbf',
    dim: '#707b8d',
    warning: '#e0af68',
    success: '#9ece6a',
    error: '#f7768e',
  }),
  themeVariant('sepia-paper', {
    accent: '#9f6b2d',
    bg: '#f5ead7',
    bgSecondary: '#fff7e9',
    bgTertiary: '#eadcc4',
    bgHover: '#dfcfb3',
    border: '#c8ad87',
    borderMuted: '#e1d0b5',
    selectedBg: '#ecd5ae',
    text: '#2f2418',
    muted: '#725f48',
    dim: '#9b8568',
    warning: '#a86f00',
    success: '#547c38',
    error: '#b4443f',
  }),
  themeVariant('high-contrast-dark', {
    accent: '#00e5ff',
    bg: '#000000',
    bgSecondary: '#080808',
    bgTertiary: '#141414',
    bgHover: '#222222',
    border: '#555555',
    borderMuted: '#303030',
    selectedBg: '#00394a',
    text: '#ffffff',
    muted: '#d0d0d0',
    dim: '#8a8a8a',
    warning: '#ffd400',
    success: '#00ff75',
    error: '#ff4a4a',
  }),
  themeVariant('high-contrast-light', {
    accent: '#0046ff',
    bg: '#ffffff',
    bgSecondary: '#f7f7f7',
    bgTertiary: '#ececec',
    bgHover: '#dddddd',
    border: '#707070',
    borderMuted: '#cfcfcf',
    selectedBg: '#dce5ff',
    text: '#000000',
    muted: '#333333',
    dim: '#777777',
    warning: '#8a5900',
    success: '#006b31',
    error: '#b00020',
  }),
  themeVariant('lavender-mist', {
    accent: '#8f6ee8',
    bg: '#f6f1ff',
    bgSecondary: '#ffffff',
    bgTertiary: '#ece4fb',
    bgHover: '#e2d7f8',
    border: '#cbbbe8',
    borderMuted: '#e3d8f3',
    selectedBg: '#ded0fa',
    text: '#251b3f',
    muted: '#6f5f87',
    dim: '#9a8bae',
    warning: '#a76f00',
    success: '#33835c',
    error: '#b33b5f',
  }),
  themeVariant('terminal-green', {
    accent: '#33ff88',
    bg: '#020604',
    bgSecondary: '#07100b',
    bgTertiary: '#0b1a11',
    bgHover: '#102719',
    border: '#1f5a36',
    borderMuted: '#12351f',
    selectedBg: '#164629',
    text: '#dfffe9',
    muted: '#8bcea2',
    dim: '#578767',
    warning: '#d7ff5f',
    success: '#33ff88',
    error: '#ff5d6c',
    mdHeading: '#d7ff5f',
  }),
  themeVariant('coffeehouse', {
    accent: '#d99a5b',
    bg: '#17100d',
    bgSecondary: '#211713',
    bgTertiary: '#30211a',
    bgHover: '#3f2d24',
    border: '#60483a',
    borderMuted: '#3d2d25',
    selectedBg: '#4b3328',
    text: '#fff0df',
    muted: '#c2a28b',
    dim: '#866b59',
    warning: '#f4c06a',
    success: '#8aca83',
    error: '#e66f63',
  }),
  themeVariant('iceberg', {
    accent: '#2d7dd2',
    bg: '#edf6fb',
    bgSecondary: '#ffffff',
    bgTertiary: '#dfeef7',
    bgHover: '#d1e5f0',
    border: '#b7cfdd',
    borderMuted: '#d5e5ee',
    selectedBg: '#cfe6fa',
    text: '#102333',
    muted: '#536c7c',
    dim: '#8297a4',
    warning: '#9b6a00',
    success: '#287d55',
    error: '#bd3b4b',
  }),
];

function themeVariant(name: string, colors: ThemeColors): PiTheme {
  const accent = colors.accent ?? '#00aaff';
  const text = colors.text ?? '#e0e0e8';
  const bg = colors.bg ?? '#1a1a1e';
  const bgSecondary = colors.bgSecondary ?? bg;
  const bgTertiary = colors.bgTertiary ?? bgSecondary;
  const bgHover = colors.bgHover ?? bgTertiary;
  const border = colors.border ?? '#3a3a3e';
  const selectedBg = colors.selectedBg ?? bgHover;
  const warning = colors.warning ?? '#ffaa00';
  const success = colors.success ?? '#00cc66';
  const error = colors.error ?? '#ff4444';

  return {
    name,
    colors: {
      borderAccent: accent,
      titlebarBg: colors.titlebarBg ?? bgSecondary,
      titlebarText: colors.titlebarText ?? text,
      titlebarBorder: colors.titlebarBorder ?? border,
      titlebarHover: colors.titlebarHover ?? bgHover,
      titlebarActive: colors.titlebarActive ?? selectedBg,
      userMessageBg: colors.userMessageBg ?? selectedBg,
      userMessageText: colors.userMessageText ?? text,
      customMessageBg: colors.customMessageBg ?? selectedBg,
      customMessageText: colors.customMessageText ?? text,
      customMessageLabel: colors.customMessageLabel ?? accent,
      toolPendingBg: colors.toolPendingBg ?? bgTertiary,
      toolSuccessBg: colors.toolSuccessBg ?? bgTertiary,
      toolErrorBg: colors.toolErrorBg ?? bgTertiary,
      toolTitle: colors.toolTitle ?? accent,
      mdHeading: colors.mdHeading ?? warning,
      mdLink: colors.mdLink ?? accent,
      mdCode: colors.mdCode ?? accent,
      mdListBullet: colors.mdListBullet ?? accent,
      syntaxKeyword: colors.syntaxKeyword ?? accent,
      syntaxFunction: colors.syntaxFunction ?? accent,
      syntaxType: colors.syntaxType ?? accent,
      syntaxOperator: colors.syntaxOperator ?? accent,
      syntaxString: colors.syntaxString ?? success,
      syntaxNumber: colors.syntaxNumber ?? warning,
      thinkingMinimal: colors.thinkingMinimal ?? accent,
      thinkingLow: colors.thinkingLow ?? accent,
      thinkingMedium: colors.thinkingMedium ?? accent,
      thinkingHigh: colors.thinkingHigh ?? warning,
      thinkingXhigh: colors.thinkingXhigh ?? error,
      ...colors,
    },
  };
}

const TOKEN_VAR_ALIASES: Record<string, string[]> = {
  userMessageBg: ['--pi-user-msg-bg'],
  userMessageText: ['--pi-user-msg-text'],
  customMessageBg: ['--pi-custom-msg-bg'],
  customMessageText: ['--pi-custom-msg-text'],
  customMessageLabel: ['--pi-custom-msg-label'],
  toolDiffAdded: ['--pi-diff-added'],
  toolDiffRemoved: ['--pi-diff-removed'],
  toolDiffContext: ['--pi-diff-context'],
};

export function applyRuntimeSettings(
  settings: Pick<AppSettings, 'theme' | 'language' | 'fontSize' | 'fontFamily' | 'monoFontFamily'>,
  themes: PiTheme[] = [],
): void {
  if (typeof document === 'undefined') return;

  const root = document.documentElement;
  const runtimeTheme = resolveRuntimeTheme(settings.theme, themes);

  root.lang = settings.language;
  root.dataset.language = settings.language;
  root.dataset.theme = runtimeTheme.name;
  root.style.fontSize = `${settings.fontSize}px`;
  root.style.setProperty('--font-sans', sanitizeFontStack(settings.fontFamily, DEFAULT_FONT_FAMILY));
  root.style.setProperty('--font-display', sanitizeFontStack(settings.fontFamily, DEFAULT_FONT_FAMILY));
  root.style.setProperty('--font-mono', sanitizeFontStack(settings.monoFontFamily, DEFAULT_MONO_FONT_FAMILY));
  root.style.colorScheme = isLightTheme(runtimeTheme.colors, runtimeTheme.name) ? 'light' : 'dark';

  applyThemeColors(runtimeTheme.colors, runtimeTheme.vars);
}

function sanitizeFontStack(value: string | undefined, fallback: string): string {
  const trimmed = value?.trim();
  if (!trimmed || /[;{}]/.test(trimmed)) return fallback;
  return trimmed;
}

export function resolveRuntimeTheme(themeName: string, themes: PiTheme[] = []): PiTheme {
  const serverTheme = themes.find((theme) => theme.name === themeName);
  const baseTheme = baseThemeFor(serverTheme ?? BUILTIN_THEMES.find((theme) => theme.name === themeName), themeName);

  return {
    name: serverTheme?.name ?? themeName,
    vars: serverTheme?.vars,
    colors: {
      ...baseTheme.colors,
      ...(serverTheme?.colors ?? BUILTIN_THEMES.find((theme) => theme.name === themeName)?.colors ?? {}),
    },
    export: serverTheme?.export,
  };
}

export function listRuntimeThemes(themes: PiTheme[] = []): PiTheme[] {
  const byName = new Map<string, PiTheme>();

  for (const theme of BUILTIN_THEMES) {
    byName.set(theme.name, theme);
  }

  for (const theme of themes) {
    byName.set(theme.name, {
      ...theme,
      colors: resolveRuntimeTheme(theme.name, themes).colors,
    });
  }

  return Array.from(byName.values()).sort((a, b) => themePriority(a.name) - themePriority(b.name));
}

export function themeDisplayName(name: string): string {
  return THEME_DISPLAY_NAMES[name] ?? name.replace(/[-_]+/g, ' ').replace(/\b\w/g, (char) => char.toUpperCase());
}

function themePriority(name: string): number {
  const index = PRIORITY_THEME_NAMES.indexOf(name);
  return index === -1 ? PRIORITY_THEME_NAMES.length : index;
}

function applyThemeColors(colors: ThemeColors, vars?: Record<string, string>): void {
  const rootStyle = document.documentElement.style;

  for (const [token, value] of Object.entries(colors)) {
    for (const cssVar of cssVarsForToken(token)) {
      rootStyle.setProperty(cssVar, value);
    }
  }

  for (const [token, value] of Object.entries(vars ?? {})) {
    rootStyle.setProperty(token.startsWith('--') ? token : `--pi-${toKebab(token)}`, value);
  }
}

function cssVarsForToken(token: string): string[] {
  return [`--pi-${toKebab(token)}`, ...(TOKEN_VAR_ALIASES[token] ?? [])];
}

function baseThemeFor(theme: PiTheme | undefined, fallbackName: string): PiTheme {
  if (theme && isLightTheme(theme.colors, theme.name)) {
    return BUILTIN_THEMES[1]!;
  }

  if (!theme && fallbackName.toLowerCase().includes('light')) {
    return BUILTIN_THEMES[1]!;
  }

  return BUILTIN_THEMES[0]!;
}

function isLightTheme(colors: ThemeColors, name: string): boolean {
  const bg = colors.bg ?? colors.bgSecondary;
  if (!bg) return name.toLowerCase().includes('light');
  return relativeLuminance(bg) > 0.55;
}

function relativeLuminance(color: string): number {
  const hex = color.trim().replace(/^#/, '');
  if (!/^[0-9a-f]{6}$/i.test(hex)) return 0;

  const channels = [0, 2, 4].map((start) => {
    const value = parseInt(hex.slice(start, start + 2), 16) / 255;
    return value <= 0.03928 ? value / 12.92 : Math.pow((value + 0.055) / 1.055, 2.4);
  });

  return 0.2126 * channels[0]! + 0.7152 * channels[1]! + 0.0722 * channels[2]!;
}

function toKebab(value: string): string {
  return value.replace(/[A-Z]/g, (match) => `-${match.toLowerCase()}`);
}
